### ISSUE TITLE
pip package is broken

### ISSUE THREAD

**Issue by smspillaz** [oinume/iocapture#1]
```
Collecting iocapture
Downloading iocapture-0.1.0.tar.gz
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "/var/folders/3x/5l69_w4s02g8gcbpj25yfvsh0000gn/T/pip-build-yxxkru1t/iocapture/setup.py", line 28, in <module>
    for package in open("requirements-dev.txt").read().split("\n"):
FileNotFoundError: [Errno 2] No such file or directory: 'requirements-dev.txt'
Complete output from command python setup.py egg_info:
Traceback (most recent call last):

  File "<string>", line 20, in <module>

  File "/var/folders/3x/5l69_w4s02g8gcbpj25yfvsh0000gn/T/pip-build-yxxkru1t/iocapture/setup.py", line 28, in <module>

    for package in open("requirements-dev.txt").read().split("\n"):

FileNotFoundError: [Errno 2] No such file or directory: 'requirements-dev.txt'

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /var/folders/3x/5l69_w4s02g8gcbpj25yfvsh0000gn/T/pip-build-yxxkru1t/iocapture
```

**Comment by oinume** [comment]
Fixed in v0.1.2. Thank you for reporting and I'm sorry for slow response.
