### ISSUE TITLE
Exceptions are be silently swallowed in with block.

### ISSUE THREAD

**Issue by kierun** [oinume/iocapture#5]
I was fixing a bug in my code that could be traced to an exception being silently swallowed by `iocapture`. See the script:

```
import logging
import iocapture

logging.basicConfig(filename='example.log', level=logging.DEBUG)

err = 'eek'
with iocapture.capture() as captured:
        logging.error("{}", err)  # Raises TypeError

logging.error("Are we okay?")
```

Running this script return an error code of 0 (aka success) and the log file is:

```
; cat example.log    
ERROR:root:Are we okay?
```

Removing the `with … ` line and correcting the indent yields the expected:

```
; python ook.py
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib64/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args  
TypeError: not all arguments converted during string formatting
Logged from file ook.py, line 7 
```

**Comment by oinume** [comment]
Thank you for reporting the issue. I'm investigating.

**Comment by kierun** [comment]
You are most welcome. Let me know if you need me to test a patch -- the above code is a toy example from my production code.
